<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SolutionDir)..\_Generated\AssemblyStaticInfo.fs" Link="AssemblyStaticInfo.fs" />
    <Compile Remove="$(SolutionDir)..\_Generated\AssemblyStaticInfo.cs" Link="AssemblyStaticInfo.cs" />
    <Compile Include="DefineCmdletInTheCorrectNamespaceTest.fs" />
    <Compile Include="UseOnlyStandardVerbsTest.fs" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\FSharpExamples\FSharpExamples.fsproj" />
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\AltCode.Rules.PowerShell.fsproj" />
    <ProjectReference Include="Examples\Examples.AltCode.PowerShell.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.3" />
  </ItemGroup>

</Project>
