<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Test\**\*.cs" />
    <Compile Remove="PreferIFormatProviderOverrideRule.cs" />
    <Compile Remove="PreferOverrideBaseRule.cs" />
    <Compile Remove="PreferStringComparisonOverrideRule.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions">
      <Version>6.0.0</Version>
    </PackageReference>
  </ItemGroup>
</Project>