<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <NoWarn>$(NoWarn);1701;1702;414;219;649;169;168</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\framework\Test\csc2008\Duplicates.dll" Link="Duplicates.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AvoidLongMethodsTest.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\FSharpExamples\FSharpExamples.fsproj" />
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Rules.Smells.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Reference Include="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  </ItemGroup>
</Project>
