<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SolutionDir)..\_Generated\AssemblyStaticInfo.fs" Link="AssemblyStaticInfo.fs" />
    <Compile Include="AvoidLongParameterListsRule .fs" />
    <Compile Include="AvoidMultidimensionalIndexerRule.fs" />
    <Compile Include="AvoidNonAlphanumericIdentifierRule.fs" />
    <Compile Include="AvoidRepetitiveCastsRule.fs" />
    <Compile Include="AvoidSwitchStatementsRule.fs" />
    <Compile Include="AvoidUncalledPrivateCodeRule.fs" />
    <Compile Include="AvoidUnnecessarySpecializationRule.fs" />
    <Compile Include="AvoidUnneededFieldInitializationRule.fs" />
    <Compile Include="AvoidUnneededUnboxingRule.fs" />
    <Compile Include="AvoidUnsealedUninheritedInternalTypeRule.fs" />
    <Compile Include="BadRecursiveInvocationRule.fs" />
    <Compile Include="ConsiderConvertingMethodToPropertyRule.fs" />
    <Compile Include="DelegatesPassedToNativeCodeMustIncludeExceptionHandlingRule.fs" />
    <Compile Include="DoNotThrowInNonCatchClausesRule.fs" />
    <Compile Include="EnsureLocalDisposalRule.fs" />
    <Compile Include="MethodCanBeMadeStaticRule.fs" />
    <Compile Include="ParameterNamesShouldMatchOverridenMethod.fs" />
    <Compile Include="RemoveDependenceOnObsoleteCodeRule.fs" />
    <Compile Include="UseCorrectPrefixRule.fs" />
    <None Include="gendarming.txt" />
    <None Include="rules.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.5" />
    <PackageReference Update="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

</Project>