version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2013
configuration: Release
clone_depth: 2
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    NuGet restore .\packages.config -PackagesDirectory .\packages

    powershell .\set-version.ps1
build:
  project: .\gendarme\gendarme-win.sln
  verbosity: normal
after_build:
- cmd: NuGet pack altcode.gendarme.nuspec
artifacts:
- path: .\*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: SFuyRsZ1Ay5C4xJ19c4jPetnMcDmuFIToz2vWJvnvS6wQEDe8C+pubF6r9yIaBTH
  on:
    branch: /release.*/
notifications:
- provider: Slack
  incoming_webhook: 
    secure: yzKiNN5snmI7Vzh12NWUEKC+V/w5wGI1ZMUGPT8p5WRefjAbB6DSgYkmWnzNADq9SurhbgIE2hlcCQivCQJ5gQE3AEGFpe+V7Dh/Up/jV0U=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false  