<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <DocumentationFile />
    <NoWarn>CA2200</NoWarn>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>