<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net7.0</TargetFrameworks>
    <NoWarn>$(NoWarn);67;169;649;661;659;660;661;628;108;114</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;DEBUG;CODE_ANALYSIS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\FSharpExamples\FSharpExamples.fsproj" />
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Rules.Design.csproj" />
  </ItemGroup>
</Project>
