<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SolutionDir)..\_Generated\AssemblyStaticInfo.fs" Link="AssemblyStaticInfo.fs" />
    <Compile Include="Augment.fs" />
    <Compile Include="ProgramDatabase.fs" />
    <Compile Include="NetCoreResolver.fs" />
  </ItemGroup>
  
</Project>