<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net7.0</TargetFrameworks>
    <NoWarn>$(NoWarn);1701;1702;SYSLIB0003;618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Permissions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Rules.Security.Cas.csproj" />
  </ItemGroup>
</Project>