<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <NoWarn>169</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gendarme.Rules.Performance\Gendarme.Rules.Performance.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Test\**\*.cs" />
  </ItemGroup>
</Project>
