<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Gendarme</RootNamespace>
    <TargetFrameworks>netcoreapp2.1;net472</TargetFrameworks>
    <PackAsTool Condition="'$(TargetFramework)' != 'net472'">True</PackAsTool>
    <ApplicationIcon>$(SolutionDir)swf-wizard-runner\Resources\gendarme.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineConstants>TRACE;RELEASE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <PreBuildEvent />
    <PostBuildEvent />
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(SolutionDir)..\_Generated\AssemblyStaticInfo.cs" />
    <Content Include="..\rules\rules.xml" Link="rules.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="DotnetToolSettings.xml">
      <CopyToOutputDirectory Condition="'$(TargetFramework)' != 'net472'">PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\framework\Gendarme.Framework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="ChangeLog" />
    <EmbeddedResource Include="gendarme.xsd" />
    <EmbeddedResource Include="gendarme.xsl" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>