//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gendarme {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gendarme.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} assemblies processed in {1}..
        /// </summary>
        internal static string AssembliesProcessed {
            get {
                return ResourceManager.GetString("AssembliesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : {0}.
        /// </summary>
        internal static string ColonValue {
            get {
                return ResourceManager.GetString("ColonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} defects found. {1}.
        /// </summary>
        internal static string DefectsFound {
            get {
                return ResourceManager.GetString("DefectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing option &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string ErrorParsingOption {
            get {
                return ResourceManager.GetString("ErrorParsingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gendarme - Development Snapshot.
        /// </summary>
        internal static string GendarmeSnapshot {
            get {
                return ResourceManager.GetString("GendarmeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gendarme v{0}.
        /// </summary>
        internal static string GendarmeVersion {
            get {
                return ResourceManager.GetString("GendarmeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: gendarme [--config file] [--set ruleset] [--{log|xml|html} file] assemblies
        ///Where
        ///  --config file		Specify the rule sets and rule settings. Default is &apos;rules.xml&apos;.
        ///  --set ruleset		Specify a rule set from configfile. Default is &apos;default&apos;.
        ///  --log file		Save the report to the specified file.
        ///  --xml file		Save the report, as XML, to the specified file.
        ///  --html file		Save the report, as HTML, to the specified file.
        ///  --ignore file		Do not report defects listed in the specified file.
        ///  --limit  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        internal static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If, and only if, this message refers to an assembly mentioned
        ///in a &apos;Resolved assembly reference&apos; message above, then it is a bug.
        ///If so, please report the entire stack trace..
        /// </summary>
        internal static string MaybeBugReport {
            get {
                return ResourceManager.GetString("MaybeBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assemblies were specified to be analysed..
        /// </summary>
        internal static string NoAssembliesSpecified {
            get {
                return ResourceManager.GetString("NoAssembliesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No defects found. {0}.
        /// </summary>
        internal static string NoDefectsFound {
            get {
                return ResourceManager.GetString("NoDefectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One assembly processed in {0}..
        /// </summary>
        internal static string OneAssemblyProcessed {
            get {
                return ResourceManager.GetString("OneAssemblyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One defect found. {0}.
        /// </summary>
        internal static string OneDefectFound {
            get {
                return ResourceManager.GetString("OneDefectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {1} can&apos;t be found in the rule {0}.
        /// </summary>
        internal static string PropertyNotInRule {
            get {
                return ResourceManager.GetString("PropertyNotInRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {1} can&apos;t be written in the rule {0}.
        /// </summary>
        internal static string PropertyUnwriteableInRule {
            get {
                return ResourceManager.GetString("PropertyUnwriteableInRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.  Review your configuration file.&quot;.
        /// </summary>
        internal static string ReviewConfigurationFile {
            get {
                return ResourceManager.GetString("ReviewConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule:	{0}.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule with name {0} doesn&apos;t exist.
        /// </summary>
        internal static string RuleDoesntExist {
            get {
                return ResourceManager.GetString("RuleDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace: {0}.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target:	{0} ({1}).
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TearDown: {0}.
        /// </summary>
        internal static string TearDown {
            get {
                return ResourceManager.GetString("TearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uncaught exception occurred. Please fill a bug report at https://github.com/SteveGilham/Gendarme/issues.
        /// </summary>
        internal static string UncaughtException {
            get {
                return ResourceManager.GetString("UncaughtException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration parameters do not match any known rule..
        /// </summary>
        internal static string UnmatchedConfigurationParameters {
            get {
                return ResourceManager.GetString("UnmatchedConfigurationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{2}&apos; could not be converted into the property {1} type for rule {0}.
        /// </summary>
        internal static string ValueCannotBeConverted {
            get {
                return ResourceManager.GetString("ValueCannotBeConverted", resourceCulture);
            }
        }
    }
}
