<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <NoWarn>1701;1702;618;649;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\FSharpExamples\FSharpExamples.fsproj" />
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Rules.BadPractice.csproj" />
    <ProjectReference Include="Examples\Examples.Rules.BadPractice\Examples.Rules.BadPractice.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AvoidNullCheckWithAsOperatorTest.cs" />
    <Compile Remove="DoNotDecreaseVisibilityTest.cs" />
    <Compile Remove="Examples\**\*.cs" />
  </ItemGroup>
</Project>