<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Test\**\*.cs" />
    <None Include="ChangeLog" />
    <None Remove="2.8-4.0-defs.zip" />
    <EmbeddedResource Include="2.8-4.0-defs.zip" />
  </ItemGroup>
</Project>