<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <NoWarn>414;168;169;649;628</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Rules.Serialization.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="MarkEnumerationsAsSerializableTest.cs" />
  </ItemGroup>
</Project>
