<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net7.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);1701;1702;SYSLIB0003;649;67;660;661;108;659;414;1718;169;168;219</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;DEBUG;CODE_ANALYSIS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Examples\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FSharpExamples\FSharpExamples.fsproj" />
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Rules.Performance.csproj" />
    <ProjectReference Include="Examples\Examples.Rules.Performance.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'net472'">
    <PackageReference Include="System.Security.Permissions" />
  </ItemGroup>
</Project>