<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildThisFileDirectory)..\..\rules\Test.Build.props" />
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <NoWarn>1701;1702;618;219;169;649;414;67</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\rules\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Framework.csproj" />
  </ItemGroup>
</Project>
