<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildThisFileDirectory)..\..\rules\Test.Build.props" />
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <NoWarn>1701;1702;618;219;169;649;414;67</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="MCSRetro\**" />
    <None Remove="MCSRetro\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="csc2008\StackBadBoysR.dll" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\rules\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Framework.csproj" />
  </ItemGroup>
</Project>
