<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <None Include="dataflow\BasicBlock.cs" />
    <None Include="dataflow\CFG.cs" />
    <None Include="dataflow\CFGEdge.cs" />
    <None Include="dataflow\Dataflow.cs" />
    <None Include="dataflow\IDataflowAnalysis.cs" />
    <None Include="graph\DFS.cs" />
    <None Include="graph\Edge.cs" />
    <None Include="graph\Graph.cs" />
    <None Include="graph\IEdge.cs" />
    <None Include="graph\IGraph.cs" />
    <None Include="graph\INode.cs" />
    <None Include="graph\Node.cs" />
    <None Include="NonNullAttribute.cs" />
    <None Include="NonNullAttributeCollector.cs" />
    <None Include="NullDerefAnalysis.cs" />
    <None Include="NullDerefFrame.cs" />
    <None Include="NullDerefRule.cs" />
    <None Include="Nullity.cs" />
    <None Include="ChangeLog" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Test\**\*.cs" />
    <Compile Remove="dataflow\BasicBlock.cs" />
    <Compile Remove="dataflow\CFG.cs" />
    <Compile Remove="dataflow\CFGEdge.cs" />
    <Compile Remove="dataflow\Dataflow.cs" />
    <Compile Remove="dataflow\IDataflowAnalysis.cs" />
    <Compile Remove="graph\DFS.cs" />
    <Compile Remove="graph\Edge.cs" />
    <Compile Remove="graph\Graph.cs" />
    <Compile Remove="graph\IEdge.cs" />
    <Compile Remove="graph\IGraph.cs" />
    <Compile Remove="graph\INode.cs" />
    <Compile Remove="graph\Node.cs" />
    <Compile Remove="NonNullAttribute.cs" />
    <Compile Remove="NonNullAttributeCollector.cs" />
    <Compile Remove="NullDerefAnalysis.cs" />
    <Compile Remove="NullDerefFrame.cs" />
    <Compile Remove="NullDerefRule.cs" />
    <Compile Remove="Nullity.cs" />
    <Compile Remove="DeclareEventsExplicitlyRule.cs" />
  </ItemGroup>
</Project>