<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="1.1.1" PrivateAssets="All" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="1.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Mono.Cecil" Version="0.11.4" />
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="System.Security.Permissions" Version="6.0.0" />
    <PackageVersion Update="FSharp.Core" Version="6.0.6" />
    <PackageVersion Include="System.Resources.Extensions" Version="6.0.0" />
    <PackageVersion Include="altcover" Version="8.4.840" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageVersion Include="NUnit" Version="3.13.3" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Update="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="6.0.1" />
    <PackageVersion Include="PowerShellStandard.Library" Version="5.1.1" />
  </ItemGroup>
</Project>