<Project>
  <Import Project="$(MSBuildThisFileDirectory)\..\OutputBuildProps.props" />
  <PropertyGroup Label="OutputBuildProps">
    <SolutionDir Condition="'$(SolutionDir)' == ''">$(MSBuildThisFileDirectory)</SolutionDir>
    <DocumentationFile />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>TRACE;DEBUG;CODE_ANALYSIS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'!='Debug'">
    <DefineConstants>TRACE;RELEASE</DefineConstants>
  </PropertyGroup>
</Project>