<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <NoWarn>$(NoWarn);1701;1702;SYSLIB0003;114;67;108;169</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\FSharpExamples\FSharpExamples.fsproj" />
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\Gendarme.Rules.Naming.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AvoidRedundancyInMethodNameTest.cs" />
    <Compile Remove="AvoidRedundancyInTypeNameTest.cs" />
  </ItemGroup>
</Project>
