<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="ChangeLog" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="DoNotThrowInNonCatchClausesRule.cs" />
    <Compile Remove="Test\**\*.cs" />
  </ItemGroup>
</Project>
