<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Sample1.exe" />
    <Compile Include="$(SolutionDir)..\_Generated\AssemblyStaticInfo.fs" Link="AssemblyStaticInfo.fs" />
    <Compile Remove="$(SolutionDir)..\_Generated\AssemblyStaticInfo.cs" Link="AssemblyStaticInfo.cs" />
    <Compile Include="AvoidAssemblySemanticVersionMismatchTest.fs" />
    <Compile Include="JustifySuppressionTest.fs" />
    <Compile Include="PreferStrongNamedAssembliesTest.fs" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include=".\Examples\Examples.AltCode.General.csproj" />
    <ProjectReference Include="..\..\Test.Rules\Test.Rules.csproj" />
    <ProjectReference Include="..\AltCode.Rules.General.fsproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.5" />
  </ItemGroup>

</Project>
