<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <NoWarn>1590</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningsAsErrors>1571</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <WarningsAsErrors>1570</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Test\**\*.cs" />
    <EmbeddedResource Remove="Test\**\*.resx" />
  </ItemGroup>
</Project>
